@backend_HostAddress = https://localhost:7110

### Get all books
GET {{backend_HostAddress}}/api/books
Accept: application/json

###

### Add a new book
POST {{backend_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "New Book Title",
  "author": "Author Name",
  "year": 2024
}

###

### Update an existing book (change the ID accordingly)
PUT {{backend_HostAddress}}/api/books/1
Content-Type: application/json

{
  "id": 1,
  "title": "Updated Book Title",
  "author": "Updated Author",
  "year": 2025
}

###

### Delete a book by ID
DELETE {{backend_HostAddress}}/api/books/1


